# Generated by Django 2.1.1 on 2019-05-14 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specific_todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_priority', models.IntegerField(default=0)),
                ('content', models.CharField(max_length=200)),
                ('is_checked', models.BooleanField(default=False)),
            ],
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='is_done',
            new_name='all_done',
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='todo_priority',
            new_name='priority',
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='todo_title',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='todo_content',
        ),
        migrations.AddField(
            model_name='specific_todo',
            name='todo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todos.Todo'),
        ),
    ]
