# Generated by Django 2.1.1 on 2019-05-16 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_auto_20190514_1726'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='done',
            name='todo',
        ),
        migrations.AddField(
            model_name='todo',
            name='done_date',
            field=models.DateTimeField(default=None, verbose_name='done date'),
        ),
        migrations.DeleteModel(
            name='Done',
        ),
    ]
