# Generated by Django 2.1.1 on 2019-05-16 08:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0003_auto_20190516_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='done_date',
            field=models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0), verbose_name='done date'),
        ),
    ]
