# Generated by Django 2.1.1 on 2019-05-16 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0004_auto_20190516_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='done_date',
            field=models.DateTimeField(default=None, verbose_name='done date'),
        ),
    ]
