# Generated by Django 2.1.1 on 2019-05-16 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0006_auto_20190516_2145'),
    ]

    operations = [
        migrations.CreateModel(
            name='Done',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('done_date', models.DateTimeField(verbose_name='date that todo is done')),
            ],
        ),
        migrations.RemoveField(
            model_name='todo',
            name='done_date',
        ),
        migrations.AlterField(
            model_name='todo',
            name='pub_date',
            field=models.DateTimeField(verbose_name='date published'),
        ),
        migrations.AddField(
            model_name='done',
            name='todo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='todos.Todo'),
        ),
    ]
