# Generated by Django 2.1.1 on 2019-05-17 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0007_auto_20190516_2220'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'ordering': ['priority']},
        ),
        migrations.RemoveField(
            model_name='specific_todo',
            name='sub_priority',
        ),
    ]
